---
abstract: 'URI constraint/filter for Data::FormValidator'
author:
  - 'Graham TerMarsch (cpan@howlingfrog.com)'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-FormValidator-URI
provides:
  Data::FormValidator::URI:
    file: lib/Data/FormValidator/URI.pm
    version: 0.02
requires:
  Data::FormValidator: 4
  URI: 0
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: 0.02
